name: Rust
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          for dir in task__*/; do
            if [ -d "$dir" ]; then
              echo "Building in $dir"
              cd "$dir"
              cargo build --verbose
              cd ..
            fi
          done
      - name: Run tests
        run: |
          for dir in task__*/; do
            if [ -d "$dir" ]; then
              echo "Testing in $dir"
              cd "$dir"
              cargo test --verbose
              cd ..
            fi
          done
